#!/usr/bin/env python
from __future__ import absolute_import, division, print_function
import cv2 as cv
import numpy as np
from numpy.lib.recfunctions import structured_to_unstructured
from ros_numpy import msgify, numpify
import rospy
from sensor_msgs.msg import CompressedImage, Image, PointCloud2


class CloudToDepth:
    def __init__(self):
        self.negative = rospy.get_param('~negative', False)
        self.image_pub = rospy.Publisher('image', Image, queue_size=2)
        self.compressed_pub = rospy.Publisher(self.image_pub.resolved_name + '/compressed', CompressedImage, queue_size=2)
        self.cloud_sub = rospy.Subscriber('cloud', PointCloud2, self.on_cloud, queue_size=2)

    def on_cloud(self, cloud_msg):
        if self.image_pub.get_num_connections() == 0 and self.compressed_pub.get_num_connections() == 0:
            return
        cloud = numpify(cloud_msg)
        cloud = structured_to_unstructured(cloud[['x', 'y', 'z']])
        depth = 1000.0 * np.linalg.norm(cloud, 2, axis=-1)
        depth = depth.clip(np.iinfo(np.uint16).min, np.iinfo(np.uint16).max)
        depth = depth.astype(np.uint16)
        if self.negative:
            depth[depth > 0] = 2**16 - depth[depth > 0]
        if self.image_pub.get_num_connections():
            depth_msg = msgify(Image, depth, 'mono16')
            depth_msg.header = cloud_msg.header
            self.image_pub.publish(depth_msg)
        if self.compressed_pub.get_num_connections():
            compressed_msg = CompressedImage()
            compressed_msg.header = cloud_msg.header
            compressed_msg.format = 'mono16; png compressed'
            compressed_msg.data = cv.imencode('.png', depth, [cv.IMWRITE_PNG_COMPRESSION, 5])[1].tobytes()
            self.compressed_pub.publish(compressed_msg)


def main():
    rospy.init_node('cloud_to_depth', log_level=rospy.INFO)
    node = CloudToDepth()
    rospy.spin()


if __name__ == '__main__':
    main()
